config/routes.rb
Rails.application.routes.draw do

   devise_for :users
  resources :articles do
    resources :comments
  end
  resources :users

  # resources :welcome do
  root to: 'articles#index'
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
# module Deviseapp
#   class Application < Rails ::Application
#
#   ActionMailer::Basesmtp_setting={
#
#       :address => 'smtp.gmail.com',
#       :domain => ' mail.google.com',
#       :port => 587,
#       :user_name => 'qasimali7566675@gmail.com',
#       :password => 'weakpass',
#       :authentication => 'login',
#       :enable_starttls_auto => true
#   }
#   end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 5 }
  paginates_per 5

  # def self.search(search)
  #   if search
  #     where("title ILIKE ? ", "%#{:search}%")
  #   else
  #     all
  #   end
  # end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum role: [:standard, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :standard
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def create
    @article = current_user.articles.new(article_params)
    if @article.save

      @article.tags.create(line: params[:line])
      redirect_to @article
    else
      render 'new'
    end
  end

  def index

    # @articles= Article.search(params[:search])
    # ====== Simple search ======
    # if params[:search].present?
    #
    #   @articles = Article.where("title ILIKE ? ", "%#{params[:search]}%").order(:title).page(params[:page])
    # else
    #   @articles = Article.order(:title).page(params[:page])
    # end
    # ======== END=============
    # =======Ransack=========
    @q = Article.ransack(params[:q])

    if @q.present?
      @articles = @q.result.page(params[:page])
    else
      @articles = Article.all.page(params[:page])
    end

  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path

  end

  def show
    @article = Article.find(params[:id])

  end

  def new
    @article = Article.new
  end

  private
  def article_params
    params.require(:article).permit(:title, :body,:image)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create

    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
      @comment.user_id = current_user.id
      @comment.save
      redirect_to article_path(@article)

  end

  def show
    @comments = Comment.all
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if current_user.id ==  @comment.user.id
      @comment.destroy
      redirect_to article_path(@article)
    else
      redirect_to article_path(@article)
     end
  end


  def comment_params
    params.require(:comment).permit(:name, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @users =User.all
    @q = User.ransack(params[:q])

    if @q.present?
      @users = @q.result.page(params[:page])
    else
      @users = User.all.page(params[:page])
    end
  end

  def destroy

    @user = User.find(params[:id])
      if current_user.id == @user.id
        flash.now[:danger] = 'Invalid action perform'
        redirect_to users_path

      else
        @user.destroy
        redirect_to users_path
      end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">RailsBlog</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%=link_to 'Home', articles_path %></a></li>

    </ul>
  </div>
</nav>
<h1 class="heading1">Edit article</h1>

<%= form_with(model: @article, local: true) do |form| %>

  <%# if @article.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2>-->
<!--        <%#= pluralize(@article.errors.count, "error") %> prohibited-->
<!--        this article from being saved:-->
<!--      </h2>-->
<!--      <ul>-->
        <%# @article.errors.full_messages.each do |msg| %>
<!--          <li><%#= msg %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

  <div class="center">
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, class:'input-field' %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :body ,'data-provider': :summernote,class:'input-field'  %>
  </p>

  <p>
    <%= form.submit 'Update', class:'btn btn-success' %>
    <%= link_to 'Back', articles_path, class:'btn btn-info'%>
  </p>

<% end %>

</div>

app/views/articles/index.html.erb
<div style="bgcolor:linen;" >
  <!--      NAvBAR-->
  <nav class="navbar navbar-inverse " >
    <div class="container-fluid">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <a class="navbar-brand" href="articles">RailsBlog</a>
          <li class="active"><%= link_to 'Home', articles_path%></li>
        </ul>
        <ul class="nav navbar-nav">
          <% if current_user.present? %>
            <% if current_user.role == "admin"%>
              <li class="active"><%= link_to 'Users', users_path%></li>
            <%end %>
          <%end %>
        </ul>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a><span class="glyphicon glyphicon-user" > <%= current_user.present? ?  current_user.email : ''%></span></a></li>
        <%if current_user.present? %>
          <li><%= link_to "Logout",  destroy_user_session_path,method: :delete %></li>
        <%else   %>
          <li><%= link_to 'Login', user_session_path%></li>
        <%end %>
      </ul>

    </div>
  </nav>
  <h1 class="heading1">Index</h1>
  <br>
  <div class="center1">
    <div class="row">
      <div class="col-md-6">
        <% if current_user.present? %>
          <div><%= link_to 'Add', new_article_path, class:'btn btn-success'%></div>
        <%else %>
          <br>
        <%end %>
      </div>
      <div class="col-md-6">
        <div class="pull-right search-field ">
          <%= search_form_for @q do |f| %>
            <%= f.label :name_cont ,"Article Contain"%>
            <%= f.search_field :title_cont ,class:'search-field-shape' %>

            <!--          # Search if an associated articles.title starts with...-->
            <%#= f.label :articles_title_start %>
            <%#= f.search_field :articles_title_start %>

            <!--          # Attributes may be chained. Search multiple attributes for one value...-->
            <%#= f.label :name_or_description_or_email_or_articles_title_cont %>
            <%#= f.search_field :name_or_description_or_email_or_articles_title_cont %>

            <%= f.submit "Search", class:'btn btn-info' %>
          <% end %>
        </div>
      </div>
    </div>
    <br>


    <section id="section-works" class="section appear clearfix">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="portfolio-items isotopeWrapper clearfix" id="3">
                <% @articles.each do |article| %>
                  <article class="col-md-4" >
                    <div class="imgBlock">
                      <div class="img-container">
                   <%= image_tag("img/logo2.jpg") %>
                        </div>
                      <div class="img-overlay">
                        <p class="img-btn">
                          <span class="date"><%= article.created_at.strftime("%m/%d/%Y ")  %></span>
                          <span>|</span>
                          <a class="url-text" href="#"><%=article.user.name %></a>
                        <h2 class="h2-text">
                          <a href="#"><%= link_to strip_tags(article.title).truncate(50), article_path(article) %></a>
                        </h2>
                        </p>
                      </div>
                    </div>
                  </article>
                <% end %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>
    <div class="pull-right"><%= paginate @articles%></div>
  </div>

</div>




</div>

app/views/articles/new.html.erb
<%= form_with scope: :article,  url: articles_path, method: :post , local: true do |form| %>


  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">RailsBlog</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home', articles_path%></li>

      </ul>
    </div>
  </nav>
  <h1 class="heading1"> Add Article </h1>

<div class="center">

  <p>
    <%= form.label :title , style:'text-align:left' %><br>
    <%= form.text_field :title, placeholder:'Title',class:'input-field'   %>
  </p>
  <p>
    <%= form.label :tag , style:'text-align:left' %><br>
    <input type="text" class="input-field" name="line"  placeholder="Tags",>

  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :body, 'data-provider': :summernote, class:'center' %>

  </p>
  <p>
    <%= form.label :photo %>
    <%= form.file_field :image , required:true %>
  </p>
  <p>
    <%= form.submit 'Save', class:'btn btn-success' %>
  <%= link_to 'Back', articles_path, class:'btn btn-info'%>
  </p>
  <% end %>

</div>

app/views/articles/show.html.erb
<body style="background-color:white ; height:100%;">
<nav class="navbar navbar-inverse ">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">RailsBlog</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Home', articles_path%></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span><%= current_user.present? ?  current_user.email : ''%> </a></li>
      <li><% if current_user.present? %>
          <%= link_to "Logout",  destroy_user_session_path,method: :delete , class: 'btn'%>
        <%else %>
          <%= link_to "Login", user_session_path %>
        <%end %></li>

    </ul>
  </div>
</nav>

<div class="center">

  <h2><%= @article.title%></h2><br>
  <!--    <div class="panel-body"> <%#= @article.body  %></div>-->
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-1">
        <img src="/img/user.jpg" alt="User image" class="user_image">

      </div>
      <div class="col-md-6" style="margin-left:10px;">
        <p>
          <strong><%= @article.user.name %></strong>

          <%= link_to 'Follow', articles_path, class:'btn btn-info'%>
        </p>
        <p><%= @article.created_at.strftime("%m/%d/%Y %I:%M%p")  %></p>
      </div>
      <strong>#<%@article.tags.each do |t|%>
        <%= t.line %>
          <%end %></strong>
    </div>
  </div>

  <!--    <img src="/img/logo1.jpg" alt="User image" class="comment_image">-->

  <div class="center1">
    <%#= image_tag(@article.image)  %>
    <%= image_tag("img/logo2.jpg") %>

  </div>

  <br>
  <%= sanitize @article.body , tags: %w(strong em a b font br p table tbody tr td ol li u img iframe span blockquote pre h1 h2 h3 h4 h5 h6 div strike hr),
               attributes: %w(href face class src style ta rget frameborder width height color)%>


</div>

<div class="center">
  <%if current_user.present? %>
    <% if current_user.id == @article.user.id %>


      <%= link_to 'Edit', edit_article_path(@article),class:'btn btn-warning' %>
    <%end %>
  <%end %>

  <%if current_user.present? %>
    <% if current_user.id == @article.user.id %>
      <%= link_to 'Destroy', article_path(@article), method: :delete, class:'btn btn-danger', data: { confirm: 'Are you sure?' } %>
    <%end %>
  <%end %>

  <section class="section comments">
    <div class="container">
      <div class="comment-form">

        <% if current_user.present? %>
          <h3 class="subtitle is-3", style="color:#2E2F30; font-family: Times New Roman; ">Leave a reply</h3>
          <%= render 'comments/form' %>
        <%end %>
      </div>
      <h2 class="subtitle is-5"><strong><%= @article.comments.count %></strong> Comments</h2>
      <%= render @article.comments %>

    </div>
  </section>
</div>

</body>

app/views/comments/_comment.html.erb
<div class="box" >
  <article class="media">
    <div class="media-content">

      <p >
      <div class="col-md-1">
        <img src="/img/user.jpg" alt="User image" class="comment_image">

      </div>
      <strong><%= comment.user.name %>:</strong>
      <div class="center_comment"><%= comment.comment %></div>
      </p>

      <% if current_user.present?  %>
        <% if current_user.admin? || comment.user.id == current_user.id %>
          <div class="centerDel">
            <%= link_to 'Delete',article_comment_path(@article,comment),
                        method: :delete, class: "btn is-danger", data: { confirm: 'Are you sure?' } %></div>
        <%end %>
      <%end %>

    </div>
  </article>
</div>

app/views/comments/_form.html.erb
<%= form_for :comment, url: article_comments_path(@article), method: :post do |f| %>
  <!--
  collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
  -->
  <!--  <div class="field">-->
  <!--    <div class="control">-->
  <%#= f.text_field :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' },class:'form-control',placeholder:'Name', style:'margin-left:30px;margin-top:20px;margin-bottom:5px;width:40%;' %>
  <!--    </div>-->
  <!--  </div>-->

  <div class="field">
    <div class="control">
      <%= f.text_field :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' },class:'form-control', style:'margin-left:30px;width:70%;',placeholder:'Type something here...'  %>
    </div>
  </div>
  <%= f.submit 'Leave a reply',class:'btn btn-info', style:'margin:30px;' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/summernote/0.6.6/summernote.min.css'>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>
<!--<script type="text/javascript">-->
<!--    $(document).ready(function() {-->
<!--        $('#article_body').summernote({height: 200});-->
<!--    });-->
<!--</script>-->

app/views/users/index.html.erb
<div style="bgcolor:linen;height: 100%">
  <!--      NAvBAR-->
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">RailsBlog</a>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', articles_path%></li>
        </ul>

      </div>
      <ul class="nav navbar-nav">
        <li class="active"></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a><span class="glyphicon glyphicon-user" > <%= current_user.present? ?  current_user.email : ''%></span></a></li>
        <%if current_user.present? %>
          <li><%= link_to "Logout",  destroy_user_session_path,method: :delete %></li>
        <%else   %>
          <li><%= link_to 'Login', user_session_path%></li>
        <%end %>
      </ul>

    </div>
  </nav>

  <h1  style="text-align: center; text-transform: uppercase; color: #4CAF50;" >Users</h1>
  <div class="search-field pull-right"><%= search_form_for @q do |f| %>
      <!--  # Search if an associated articles.title starts with...-->
      <%#= f.label :articles_title_start %>
      <%#= f.search_field :articles_title_start %>

      <!--  # Attributes may be chained. Search multiple attributes for one value...-->
      <%= f.label :name_or_email_cont,"Name/Email Contain" %>
      <%= f.search_field :name_or_email_cont ,class:'search-field-shape' %>

      <%= f.submit "Search", class:'btn btn-info' %>
    <% end %>
  </div>



  <div class="container" style="margin-top: 80px">
    <div class="row">
      <div class="col-md-12">
        <table  class="table table-striped table-bordered table-hover">
          <tr  style=" background-color:navy; color:blanchedalmond">
            <th>User_id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Show</th>
            <% if current_user.present? %>
              <% if current_user.admin? %>
                <th >Delete</th>
              <%end %>
            <%end %>

          </tr>
          <% @users.each do |user| %>

            <tr>
              <td><%= user.id %></td>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.role %></td>
              <% if current_user.present? %>
                <% if current_user.admin? %>
                  <td><%= link_to 'Delete', user_path(user),
                                  method: :delete, class:'btn btn-danger',
                                  data: { confirm: 'Are you sure?' } %></td>
                  <%end %>
                <%end %>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>

          <% end %>
        </table>

      </div>
    </div>
  </div>


</div>
</div>

app/views/users/show.html.erb
<body style="background-color:white ; height:100%;">
<nav class="navbar navbar-inverse ">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">RailsBlog</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Home', articles_path%></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span><%= current_user.present? ?  current_user.email : ''%> </a></li>
      <li><% if current_user.present? %>
          <%= link_to "Logout",  destroy_user_session_path,method: :delete , class: 'btn'%>
        <%else %>
          <%= link_to "Login", user_session_path %>
        <%end %></li>

    </ul>
  </div>
</nav>
<h1 class="heading1 " >User Details</h1>
<div class="center">
  <div class="col-md-10">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>User Id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%=@user.id %></td>
        <td><%=@user.name %></td>
        <td><%=@user.email %></td>
        <td><%=@user.role %></td>
      </tr>

      </tbody>
    </table>


  </div>
</div>